### ISSUE TITLE
robot_commander.html missing from image?

### ISSUE THREAD

**Issue by jimwhitfield** [UbiquityRobotics/learn#18]
When going through your tutorial, on the page
https://ubiquityrobotics.github.io/learn/robot_commander

I am unable to run
 https://10.42.0.1/speechcommands.html 

First, I thought it would be just that there's no https server, which is true, so I removed the s
http://10.42.0.1/speechcommands.html

I believe nginx serves files from /var/www
```
ubuntu@ubiquityrobot:~$ find /var/www -print
/var/www
/var/www/html
/var/www/html/index.nginx-debian.html
```

**Comment by MoffKalast** [comment]
This is a rather old issue so I presume it was solved at some point, and since by now Robot Commander is generally deprecated and to be replaced by EZ-Map Lite I'll close this.
