### ISSUE TITLE
Can we make robot commander default to the correct IP

### ISSUE THREAD

**Issue by davecrawley** [UbiquityRobotics/learn#5]
Right now we are telling our users to enter an IP of lots of letters numbers and symbols in to robot commander. They need to enter something that is different, slightly to the default.

Why don't we just make the default in robot commander either
a) The thing that you need on first boot of the robot as per our instructions
b) The last thing you entered (I think that is already implemented)

**Comment by rohbotics** [comment]
@jrlandau can this be done?

**Comment by jrlandau** [comment]
We already do one of DC's suggestions, and there's no reason why we can't
do the other.  Also note, we do zeroconf,
