### ISSUE TITLE
How to drive with a laptop using keyboard teleop assumes infrastructure that hasn't been set up.

### ISSUE THREAD

**Issue by davecrawley** [UbiquityRobotics/learn#8]
In the quick-start guide: "How to drive with a laptop using keyboard Teleoperation in AP mode"

We talk about connecting to your work-station. However at this point we haven't told people how to set up a workstation yet, nor have we provided a link to them on how to do this or even told them its necessary.

**Comment by jrlandau** [comment]
Has been fixed
