### ISSUE TITLE
Try to install sudo apt install ROS-kinetic-magni-robot as per instructions and doesn't work

### ISSUE THREAD

**Issue by davecrawley** [UbiquityRobotics/learn#9]
In these instructions it says that installation of our software can be achieved using:

sudo apt install ROS-kinetic-magni-robot

However when I try this I get:

E: Unable to locate package ROS-kinetic-magni-robot

does the package name as it is in the documentation contain a typo?

**Comment by rohbotics** [comment]
It should be `sudo apt install ros-kinetic-magni-robot` all lowercase.
